### ISSUE TITLE
filter hijinx

### ISSUE THREAD

**Issue by yetibeard** [sinsofangels/stacks#5]
So here's my library books page numbers:
25, 1000000, 2000, 3500, 300

On a fresh refresh, with no filters having been applied, if I filter pages between 0 and 2000, it only returns one book, the book with 1000000 pages.

On a fresh refresh, no filters applied, if I filter pages between 500 and 5000, it returns with no books.
If I then reset the filter (without refreshing), and then filter 0 to 2000, like the first time, it still returns with no books.

**Comment by RococoCoding** [comment]
DOM returning input from NUMBERS INPUT was a string for .... reasons? parseInt saves the day
